apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pam-client-service-knative-pipeline-v0-run-
spec:
  pipelineRef:
    name: pam-client-service-knative-pipeline-v0
  params:
    - name: application
      value: ${APP_NAME}
    - name: source-repo-url
      value: ${SOURCE_REPO}   
    - name: source-context-path
      value: ${SOURCE_CTX_PATH}           
    - name: source-revision
      value: ${COMMIT}
    - name: short-source-revision
      value: "${SHORT_COMMIT}"
#    - name: deployment-repo-url
#      value: ${DEPLOYMENT_REPO}
#    - name: deployment-revision
#      value: master
# QUARKUS
#    - name: dockerfile
#      value: ./src/main/docker/Dockerfile.jvm
    - name: dockerfile
      value: ./src/main/docker/Dockerfile
    - name: image-registry
      value: image-registry.openshift-image-registry.svc.cluster.local:5000
    - name: image-repository
      value: ${IMAGES_NS}
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: source-pvc 
  - name: maven-settings
    configMap: 
       name: maven
#  - name: knative-kustomize-base
#    configMap: 
#       name: knative-kustomize-base
#  - name: knative-kustomize-environment
#    configMap: 
#       name: knative-kustomize-environment
