kind: Service
apiVersion: v1
metadata:
  name: hr-expenses-validations-business-service
  labels:
    app: hr-expenses-validations-business-service
spec:
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  selector:
    app: hr-expenses-validations-business-service
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}

