package com.redhat.notifications.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NotificationsModel implements java.io.Serializable {

	static final long serialVersionUID = 1L;


	private java.lang.String address;

	private java.lang.String subject;

	private java.lang.String message;

	private java.lang.String notificationId;

	public NotificationsModel() {
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getSubject() {
		return this.subject;
	}

	public void setSubject(java.lang.String subject) {
		this.subject = subject;
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public java.lang.String getNotificationId() {
		return this.notificationId;
	}

	public void setNotificationId(java.lang.String notificationId) {
		this.notificationId = notificationId;
	}

	public NotificationsModel(java.lang.String address,
			java.lang.String subject, java.lang.String message,
			java.lang.String notificationId) {
		this.address = address;
		this.subject = subject;
		this.message = message;
		this.notificationId = notificationId;
	}
	
	public String toString() { 
    return "NotificationsModel: ' Notification Address: " + this.address + "', Notification Subject: '" + this.subject + "', Notification Message: '" + this.message + "', Notification Id: '" + this.notificationId + "'";
} 

}
