kind: Service
apiVersion: v1
metadata:
  name: pam-client-service
  labels:
    app: pam-client-service
spec:
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  selector:
    app: pam-client-service
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}

